import type { Difficulty, Puzzle } from "./types.ts";

export const PUZZLES: Puzzle[] = [
  {"id":"e1","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,4],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false]},
  {"id":"e2","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,0,0,4,0,3,0,0,0,0,2,0,0,0,0,0,0,0,1],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false]},
  {"id":"e3","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,2,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,4],"wallsRight":[true,false,true,false,false,true,true,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e4","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,0,0,0,0,0,3,2,0,0,0,0,0,0,0,4,0,0,1],"wallsRight":[true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e5","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,3,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,2],"wallsRight":[false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[true,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e6","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,2,0,4,0,0,1,0,0,0,0,0,0,0,0,3,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[true,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false]},
  {"id":"e7","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,2,0,0,0,0,0,0,4,3,0,0,0,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]},
  {"id":"e8","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,4,3,0,5,0,0,0,0],"wallsRight":[true,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,true,true,false,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false]},
  {"id":"e9","difficulty":"easy","size":5,"clues":[0,0,0,0,4,0,1,0,0,0,0,3,0,0,0,0,0,0,2,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]},
  {"id":"e10","difficulty":"easy","size":5,"clues":[0,0,3,0,0,0,0,0,5,0,0,2,0,0,0,0,0,0,0,0,1,0,0,4,0],"wallsRight":[false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false],"wallsDown":[false,true,true,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m1","difficulty":"medium","size":6,"clues":[1,0,0,0,0,0,0,0,0,0,2,0,0,0,3,0,0,0,0,4,0,0,0,0,0,0,0,0,0,5,6,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,true,true,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false]},
  {"id":"m2","difficulty":"medium","size":6,"clues":[7,0,0,0,0,0,0,6,0,0,0,0,0,0,0,5,0,0,0,0,0,0,4,0,3,0,0,0,0,2,1,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,true,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false]},
  {"id":"m3","difficulty":"medium","size":6,"clues":[1,0,0,0,0,6,0,0,0,4,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,2,0,0,0,0,0,0,0,0,5,0],"wallsRight":[true,false,false,false,true,false,true,false,true,true,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m4","difficulty":"medium","size":6,"clues":[7,0,0,0,0,1,0,0,0,0,3,0,0,6,0,0,0,0,0,0,5,4,0,0,0,0,0,0,0,0,0,0,0,0,0,2],"wallsRight":[false,false,false,false,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m5","difficulty":"medium","size":6,"clues":[1,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,6,0,0,2,0,5,0,0,0,0,0,3,0,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,true,false,true,true,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false],"wallsDown":[false,true,true,false,false,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false]},
  {"id":"m6","difficulty":"medium","size":6,"clues":[7,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,3,0,0,2,0,0,0,0,0,5,0,0,0,6],"wallsRight":[false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,true,false,true,true,false,true,true,false,true,false,false,false,true,false,false,false,false,false,false,false],"wallsDown":[true,true,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false]},
  {"id":"m7","difficulty":"medium","size":6,"clues":[3,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,4,0,0,0,0,1,0,0,0,0,0,0,0,6],"wallsRight":[false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false],"wallsDown":[false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false]},
  {"id":"m8","difficulty":"medium","size":6,"clues":[0,0,0,0,0,0,5,0,7,0,0,0,0,0,6,0,0,0,0,1,0,0,0,2,0,0,0,0,3,0,0,4,0,0,0,0],"wallsRight":[false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,false,true,false,false,true,false,true,false,false],"wallsDown":[false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,true,false,false,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m9","difficulty":"medium","size":6,"clues":[1,0,0,0,0,2,6,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,4,5,0,0,0,0,0],"wallsRight":[false,true,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false,true,false,true,false,true,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,true,false,false,true,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]},
  {"id":"m10","difficulty":"medium","size":6,"clues":[0,7,0,0,2,0,0,1,0,0,0,0,0,0,0,0,3,0,6,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,4,0],"wallsRight":[false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,true,false,false],"wallsDown":[false,true,false,false,false,false,false,true,false,false,true,false,true,true,true,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h1","difficulty":"hard","size":7,"clues":[1,0,0,0,0,0,0,0,3,0,0,0,0,2,0,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,8],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,false,true,false,false,false,true,true,true,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h2","difficulty":"hard","size":7,"clues":[9,0,0,0,0,0,8,0,7,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,5,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,3,0,2,0,0,0,0,0,1],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,true,false,false,false,true,false,true,false,true,true,true,false,false,false,true,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h3","difficulty":"hard","size":7,"clues":[1,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,5,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,7,0,0,2,0,0,0,0,8],"wallsRight":[true,false,true,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,true,true,false,true,false,false,true,true,false,false,false,false,false,false,false,true,false,true,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h4","difficulty":"hard","size":7,"clues":[9,0,0,0,0,2,0,0,7,0,0,4,0,0,0,0,0,0,0,0,0,0,0,6,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,8,0,0,0,0,0,1],"wallsRight":[false,false,true,false,false,false,false,false,false,false,true,true,true,false,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,false,false,true,false,true,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h5","difficulty":"hard","size":7,"clues":[1,0,0,0,0,0,2,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,6,0,0,7,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,3],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,true,false,true,true,false,false,true,true,false,true,true,false,false,true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,false,true,true,true,false,false,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false]},
  {"id":"h6","difficulty":"hard","size":7,"clues":[9,0,0,0,0,0,8,5,0,0,0,0,0,0,0,0,0,2,0,4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,7,0,6,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,false,false,true,true,false,true,true,true,false,true,true,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false],"wallsDown":[false,true,true,false,false,false,false,false,true,true,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false]},
  {"id":"h7","difficulty":"hard","size":6,"clues":[1,0,0,0,0,2,3,0,0,0,0,0,0,0,0,4,0,0,0,0,0,5,0,0,0,6,0,0,0,0,8,0,0,0,0,7],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,false,false,true,false,false,false,false,true,true,false,true,true,false,false,false,false,false,false,false,true,false,false,true,true,false,true,true,false,false,false,false,false,false,false]},
  {"id":"h8","difficulty":"hard","size":6,"clues":[9,0,0,0,0,0,7,0,0,0,8,0,0,0,0,6,0,0,4,0,0,0,0,5,0,0,3,0,0,0,1,0,0,0,2,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,false,true,true,false,false,false,false,true,false,false,true,true,false,false,true,false,false,true,true,false,true,true,false,false,false,true,false,false,false,false,false,false,false,false]},
];

export function puzzlesFor(difficulty: Difficulty): Puzzle[] {
  return PUZZLES.filter((p) => p.difficulty === difficulty);
}

export function puzzleById(id: string): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id);
}

export function nextPuzzle(current: Puzzle): Puzzle {
  const pool = puzzlesFor(current.difficulty);
  const i = pool.findIndex((p) => p.id === current.id);
  return pool[(i + 1) % pool.length] ?? pool[0];
}

export function pickPuzzle(difficulty: Difficulty, exclude: readonly string[] = []): Puzzle {
  const pool = puzzlesFor(difficulty);
  const unused = pool.filter((p) => !exclude.includes(p.id));
  const bag = unused.length ? unused : pool;
  return bag[Math.floor(Math.random() * bag.length)] ?? pool[0];
}
