import type { Puzzle } from "./types.ts";

export const HARD: Puzzle[] = [
  {"id":"h1","difficulty":"hard","size":7,"clues":[9,0,0,0,8,0,7,0,0,0,4,0,0,0,0,0,3,0,0,0,0,0,10,0,0,0,5,0,0,0,0,0,2,0,6,0,1,0,0,0,0,0,11,0,0,0,0,0,12],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false]},
  {"id":"h2","difficulty":"hard","size":6,"clues":[0,0,0,0,0,10,0,0,0,0,0,1,9,0,0,8,0,0,0,7,0,0,2,0,0,0,5,4,0,0,6,0,0,0,0,3],"wallsRight":[false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h3","difficulty":"hard","size":6,"clues":[4,0,0,5,0,0,0,0,0,2,0,6,10,3,0,0,0,7,0,0,1,0,0,0,0,0,0,0,8,0,0,0,0,0,9,0],"wallsRight":[false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h4","difficulty":"hard","size":6,"clues":[4,0,0,0,10,0,0,0,3,2,0,0,0,5,0,0,0,0,0,6,0,0,1,0,0,0,8,9,0,0,7,0,0,0,0,0],"wallsRight":[false,true,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h5","difficulty":"hard","size":6,"clues":[6,0,0,0,0,3,0,0,5,4,0,0,0,7,0,0,2,0,0,0,1,0,0,10,8,9,0,0,0,0,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h6","difficulty":"hard","size":7,"clues":[10,0,9,0,0,0,1,0,0,0,7,0,8,0,0,0,0,0,0,0,0,0,6,0,0,0,3,0,11,0,0,0,4,0,2,0,5,0,0,0,0,0,0,0,0,0,0,0,12],"wallsRight":[false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false]},
  {"id":"h7","difficulty":"hard","size":6,"clues":[6,0,0,0,0,3,0,0,5,4,0,0,0,7,0,1,0,0,0,8,0,10,0,2,0,0,0,0,0,0,9,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h8","difficulty":"hard","size":6,"clues":[0,5,0,0,0,3,0,6,0,4,0,0,0,0,8,0,2,0,7,0,0,0,9,0,0,0,0,0,0,1,0,0,0,0,0,10],"wallsRight":[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false]},
  {"id":"h9","difficulty":"hard","size":6,"clues":[10,0,0,0,0,0,1,0,0,0,9,8,0,0,0,7,0,0,0,0,0,0,0,6,2,3,0,0,0,0,0,0,0,4,5,0],"wallsRight":[false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h10","difficulty":"hard","size":7,"clues":[0,0,0,0,0,0,9,0,3,0,2,0,10,0,4,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,8,0,0,0,0,0,11,0,6,0,0,0,7,0,0],"wallsRight":[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]},
];
