import type { Puzzle } from "./types.ts";

export const HARD: Puzzle[] = [
  {"id":"h1","difficulty":"hard","size":7,"clues":[0,0,0,0,0,0,0,0,6,0,0,0,0,0,7,0,0,0,0,0,8,0,0,0,5,0,0,0,0,0,2,0,0,0,4,0,0,0,3,0,0,0,0,0,1,0,0,0,0],"wallsRight":[false,false,false,false,true,false,false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,true,true,false,false,true,false,false,false,true,false,false,false,true,false,false,false,true,false,false,true,false,false,false,true,false,false,false,false],"wallsDown":[false,true,true,true,false,false,false,false,false,true,false,true,true,false,false,false,false,true,false,false,true,false,false,true,true,true,true,false,true,true,false,true,true,false,false,false,true,true,false,true,true,false,false,false,false,false,false,false,false]},
  {"id":"h2","difficulty":"hard","size":7,"clues":[8,0,0,0,0,0,6,0,7,0,0,0,0,0,0,0,2,0,0,0,5,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,3,0,0],"wallsRight":[true,false,false,false,false,false,false,true,true,false,true,false,false,false,true,true,true,true,false,false,false,true,true,true,false,false,true,false,true,true,true,false,false,true,false,true,true,true,false,true,true,false,false,true,false,false,true,false,false],"wallsDown":[false,false,true,true,true,true,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]},
  {"id":"h3","difficulty":"hard","size":7,"clues":[1,0,0,0,0,0,2,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,6,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,4,0,0,0,0,0,3],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,true,false,true,true,false,true,true,true,false,true,true,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false],"wallsDown":[true,true,true,true,true,true,false,false,true,true,true,true,false,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,false,false,false,false]},
  {"id":"h4","difficulty":"hard","size":7,"clues":[8,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,4,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,6,0,0,0,0,0,7],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,true,false,true,true,false,true,true,true,false,true,true,false,false,true,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false],"wallsDown":[true,true,true,true,true,true,false,false,true,true,true,true,false,false,false,false,true,true,false,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,false,false,false,false]},
  {"id":"h5","difficulty":"hard","size":6,"clues":[5,0,0,6,0,0,0,0,0,0,0,0,0,0,0,2,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,7,0],"wallsRight":[false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,true,false,false,false,true,true,false,true,false,false,true,true,false,true,false,false,false,true,true,false,false],"wallsDown":[false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,true,false,false,true,false,false,false,false,false,false,false]},
  {"id":"h6","difficulty":"hard","size":6,"clues":[0,0,0,0,0,0,4,0,0,5,6,0,1,0,3,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,7,0,0,0],"wallsRight":[false,false,true,false,false,false,false,true,false,true,false,false,true,true,false,true,false,false,true,false,true,true,false,false,true,false,false,true,false,false,false,true,false,false,false,false],"wallsDown":[false,true,false,false,true,false,true,false,true,true,false,true,false,false,false,false,true,false,false,true,true,false,false,true,false,false,true,true,true,false,false,false,false,false,false,false]},
  {"id":"h7","difficulty":"hard","size":6,"clues":[0,7,0,2,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,0,0,6,0,4,0,0,0,0,0,0,0,5],"wallsRight":[false,true,false,true,false,false,false,true,true,false,true,false,false,true,true,false,false,false,true,false,true,true,false,false,true,false,true,false,true,false,false,true,false,false,false,false],"wallsDown":[false,true,false,false,false,false,true,false,false,true,true,false,false,true,false,false,true,true,false,true,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]},
  {"id":"h8","difficulty":"hard","size":6,"clues":[0,0,6,0,0,0,0,0,0,7,0,0,0,5,0,0,0,1,0,0,0,0,0,0,4,0,0,3,2,0,0,0,0,0,0,0],"wallsRight":[false,false,true,false,false,false,false,true,true,true,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,true,false,true,true,false,false,false,false,true,false,false],"wallsDown":[false,true,false,false,true,false,true,false,false,true,false,true,false,true,true,true,true,false,true,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false]},
  {"id":"h9","difficulty":"hard","size":6,"clues":[0,0,0,0,0,0,5,0,0,4,3,0,0,0,0,0,0,0,0,0,0,2,0,0,6,1,7,0,0,0,0,0,0,0,0,0],"wallsRight":[false,false,true,false,false,false,false,true,false,true,false,false,false,true,false,true,false,false,true,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,false,false,true,true,true,true,false,true,true,true,true,false,false,false,false,false,false,false]},
  {"id":"h10","difficulty":"hard","size":6,"clues":[0,5,0,0,4,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,0,6,0,0,0,0,1,0,0,0,0,0,7],"wallsRight":[false,true,false,false,false,false,true,false,true,false,false,false,true,false,false,true,false,false,true,false,false,false,true,false,true,false,true,false,true,false,false,true,false,true,false,false],"wallsDown":[false,false,false,true,true,false,false,true,true,false,true,true,false,false,true,true,false,false,false,true,true,true,true,false,false,false,false,false,false,true,false,false,false,false,false,false]},
];
