import type { Puzzle } from "./types.ts";

export const EASY: Puzzle[] = [
  {"id":"e1","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,4],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false]},
  {"id":"e2","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,0,0,4,0,3,0,0,0,0,2,0,0,0,0,0,0,0,1],"wallsRight":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false]},
  {"id":"e3","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,2,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,4],"wallsRight":[true,false,true,false,false,true,true,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e4","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,0,0,0,0,0,3,2,0,0,0,0,0,0,0,4,0,0,1],"wallsRight":[true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,true,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e5","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,3,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,2],"wallsRight":[false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[true,true,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"e6","difficulty":"easy","size":5,"clues":[5,0,0,0,0,0,0,2,0,4,0,0,1,0,0,0,0,0,0,0,0,3,0,0,0],"wallsRight":[false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[true,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false]},
  {"id":"e7","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,2,0,0,0,0,0,0,4,3,0,0,0,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,true,false,false,false,false,true,false,true,false,true,false,false,true,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]},
  {"id":"e8","difficulty":"easy","size":5,"clues":[1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,4,3,0,5,0,0,0,0],"wallsRight":[true,false,true,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,true,true,false,false,false,false,false,false,false,true,false,false,true,true,false,false,false,false,false,false]},
  {"id":"e9","difficulty":"easy","size":5,"clues":[0,0,0,0,4,0,1,0,0,0,0,3,0,0,0,0,0,0,2,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]},
  {"id":"e10","difficulty":"easy","size":5,"clues":[0,0,3,0,0,0,0,0,5,0,0,2,0,0,0,0,0,0,0,0,1,0,0,4,0],"wallsRight":[false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false],"wallsDown":[false,true,true,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false]},
];
