import type { Puzzle } from "./types.ts";

export const MEDIUM: Puzzle[] = [
  {"id":"m1","difficulty":"medium","size":6,"clues":[0,0,0,0,0,6,0,5,0,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,2,0],"wallsRight":[false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m2","difficulty":"medium","size":6,"clues":[0,3,0,0,0,0,0,0,0,0,0,4,7,0,2,0,0,0,0,0,1,0,5,0,0,0,0,0,0,0,0,0,0,6,0,0],"wallsRight":[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,false,false,false,true,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false]},
  {"id":"m3","difficulty":"medium","size":6,"clues":[0,0,0,0,6,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,4,0,0,5,0,0,0,0,0,0],"wallsRight":[false,true,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m4","difficulty":"medium","size":6,"clues":[4,0,0,3,0,0,0,0,0,0,0,2,0,0,0,0,0,0,5,0,1,0,0,7,0,0,6,0,0,0,0,0,0,0,0,0],"wallsRight":[false,false,false,false,false,false,true,false,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m5","difficulty":"medium","size":6,"clues":[0,3,0,0,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,4,0,6,0,0,0,0,0,0,0,0,0,0,5,0,0,0],"wallsRight":[false,true,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,true,false,false,false,true,true,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m6","difficulty":"medium","size":6,"clues":[0,0,0,0,0,0,0,4,3,0,0,2,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,6,1,0,0,0,0,0,7],"wallsRight":[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,true,false,false,false,false,false,false,false,true,false,false,false,false,false,false]},
  {"id":"m7","difficulty":"medium","size":6,"clues":[6,0,0,0,0,0,1,0,5,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,3,0,0,0,0,0,0],"wallsRight":[false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m8","difficulty":"medium","size":6,"clues":[0,0,0,0,0,0,0,0,0,4,0,0,6,5,0,0,0,3,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,7,1,0],"wallsRight":[false,true,false,false,false,false,false,true,false,false,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,false,false,true,true,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]},
  {"id":"m9","difficulty":"medium","size":6,"clues":[0,0,0,5,0,0,0,0,0,0,0,0,6,0,2,0,0,0,0,0,3,0,0,4,0,1,0,0,0,0,0,0,0,0,0,0],"wallsRight":[false,true,false,false,false,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false],"wallsDown":[false,false,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false]},
  {"id":"m10","difficulty":"medium","size":6,"clues":[0,7,5,0,0,0,0,0,0,0,0,0,0,0,3,0,0,4,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,2,1],"wallsRight":[false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,true,true,false,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false],"wallsDown":[false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]},
];
